//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/C#Project/MinecraftLanguageServer/MCDocumentRule/mcdocParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ImcdocParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class mcdocParserBaseListener : ImcdocParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.logicalOR"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOR([NotNull] mcdocParser.LogicalORContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.logicalOR"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOR([NotNull] mcdocParser.LogicalORContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] mcdocParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] mcdocParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.resourceLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResourceLocation([NotNull] mcdocParser.ResourceLocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.resourceLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResourceLocation([NotNull] mcdocParser.ResourceLocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.at"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAt([NotNull] mcdocParser.AtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.at"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAt([NotNull] mcdocParser.AtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.as"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAs([NotNull] mcdocParser.AsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.as"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAs([NotNull] mcdocParser.AsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDot([NotNull] mcdocParser.DotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDot([NotNull] mcdocParser.DotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.baseDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseDataType([NotNull] mcdocParser.BaseDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.baseDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseDataType([NotNull] mcdocParser.BaseDataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.keywordType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywordType([NotNull] mcdocParser.KeywordTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.keywordType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywordType([NotNull] mcdocParser.KeywordTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.questionMark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuestionMark([NotNull] mcdocParser.QuestionMarkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.questionMark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuestionMark([NotNull] mcdocParser.QuestionMarkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeKey([NotNull] mcdocParser.TypeKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeKey([NotNull] mcdocParser.TypeKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structKeyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructKeyType([NotNull] mcdocParser.StructKeyTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structKeyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructKeyType([NotNull] mcdocParser.StructKeyTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.inject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInject([NotNull] mcdocParser.InjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.inject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInject([NotNull] mcdocParser.InjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum([NotNull] mcdocParser.EnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum([NotNull] mcdocParser.EnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.use"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUse([NotNull] mcdocParser.UseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.use"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUse([NotNull] mcdocParser.UseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDispatch([NotNull] mcdocParser.DispatchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDispatch([NotNull] mcdocParser.DispatchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.doubleDot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleDot([NotNull] mcdocParser.DoubleDotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.doubleDot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleDot([NotNull] mcdocParser.DoubleDotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] mcdocParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] mcdocParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloat([NotNull] mcdocParser.FloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloat([NotNull] mcdocParser.FloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.integerRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerRange([NotNull] mcdocParser.IntegerRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.integerRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerRange([NotNull] mcdocParser.IntegerRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] mcdocParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] mcdocParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commentary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentary([NotNull] mcdocParser.CommentaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commentary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentary([NotNull] mcdocParser.CommentaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.docCommentary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocCommentary([NotNull] mcdocParser.DocCommentaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.docCommentary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocCommentary([NotNull] mcdocParser.DocCommentaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typedNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedNumber([NotNull] mcdocParser.TypedNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typedNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedNumber([NotNull] mcdocParser.TypedNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.stringType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringType([NotNull] mcdocParser.StringTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.stringType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringType([NotNull] mcdocParser.StringTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.literalType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralType([NotNull] mcdocParser.LiteralTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.literalType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralType([NotNull] mcdocParser.LiteralTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericType([NotNull] mcdocParser.NumericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericType([NotNull] mcdocParser.NumericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.listType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListType([NotNull] mcdocParser.ListTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.listType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListType([NotNull] mcdocParser.ListTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] mcdocParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] mcdocParser.TupleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumMemberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumMemberType([NotNull] mcdocParser.EnumMemberTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumMemberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumMemberType([NotNull] mcdocParser.EnumMemberTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] mcdocParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] mcdocParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumField([NotNull] mcdocParser.EnumFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumField([NotNull] mcdocParser.EnumFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBlock([NotNull] mcdocParser.EnumBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBlock([NotNull] mcdocParser.EnumBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumType([NotNull] mcdocParser.EnumTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumType([NotNull] mcdocParser.EnumTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.prelim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrelim([NotNull] mcdocParser.PrelimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.prelim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrelim([NotNull] mcdocParser.PrelimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceType([NotNull] mcdocParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceType([NotNull] mcdocParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatcherType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDispatcherType([NotNull] mcdocParser.DispatcherTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatcherType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDispatcherType([NotNull] mcdocParser.DispatcherTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionType([NotNull] mcdocParser.UnionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionType([NotNull] mcdocParser.UnionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.staticIndexKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticIndexKey([NotNull] mcdocParser.StaticIndexKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.staticIndexKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticIndexKey([NotNull] mcdocParser.StaticIndexKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessor([NotNull] mcdocParser.AccessorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessor([NotNull] mcdocParser.AccessorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.accessorKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessorKey([NotNull] mcdocParser.AccessorKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.accessorKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessorKey([NotNull] mcdocParser.AccessorKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dynamicIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDynamicIndex([NotNull] mcdocParser.DynamicIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dynamicIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDynamicIndex([NotNull] mcdocParser.DynamicIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexWithOutDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexWithOutDynamic([NotNull] mcdocParser.IndexWithOutDynamicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexWithOutDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexWithOutDynamic([NotNull] mcdocParser.IndexWithOutDynamicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexWithDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexWithDynamic([NotNull] mcdocParser.IndexWithDynamicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexWithDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexWithDynamic([NotNull] mcdocParser.IndexWithDynamicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexBodyWithOutDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexBodyWithOutDynamic([NotNull] mcdocParser.IndexBodyWithOutDynamicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexBodyWithOutDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexBodyWithOutDynamic([NotNull] mcdocParser.IndexBodyWithOutDynamicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexBodyWithDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexBodyWithDynamic([NotNull] mcdocParser.IndexBodyWithDynamicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexBodyWithDynamic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexBodyWithDynamic([NotNull] mcdocParser.IndexBodyWithDynamicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexingOnAType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexingOnAType([NotNull] mcdocParser.IndexingOnATypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexingOnAType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexingOnAType([NotNull] mcdocParser.IndexingOnATypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeArgBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgBlock([NotNull] mcdocParser.TypeArgBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeArgBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgBlock([NotNull] mcdocParser.TypeArgBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unAttributedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnAttributedType([NotNull] mcdocParser.UnAttributedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unAttributedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnAttributedType([NotNull] mcdocParser.UnAttributedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSentence([NotNull] mcdocParser.TypeSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSentence([NotNull] mcdocParser.TypeSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.attributeSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeSet([NotNull] mcdocParser.AttributeSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.attributeSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeSet([NotNull] mcdocParser.AttributeSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.arrayLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLength([NotNull] mcdocParser.ArrayLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.arrayLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLength([NotNull] mcdocParser.ArrayLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] mcdocParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] mcdocParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.positionalValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionalValues([NotNull] mcdocParser.PositionalValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.positionalValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionalValues([NotNull] mcdocParser.PositionalValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.namedValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedValue([NotNull] mcdocParser.NamedValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.namedValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedValue([NotNull] mcdocParser.NamedValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.namedValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedValues([NotNull] mcdocParser.NamedValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.namedValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedValues([NotNull] mcdocParser.NamedValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.treeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeBody([NotNull] mcdocParser.TreeBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.treeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeBody([NotNull] mcdocParser.TreeBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.treeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeValue([NotNull] mcdocParser.TreeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.treeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeValue([NotNull] mcdocParser.TreeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] mcdocParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] mcdocParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] mcdocParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] mcdocParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDispatchStatement([NotNull] mcdocParser.DispatchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDispatchStatement([NotNull] mcdocParser.DispatchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structInjection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructInjection([NotNull] mcdocParser.StructInjectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structInjection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructInjection([NotNull] mcdocParser.StructInjectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumInjection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumInjection([NotNull] mcdocParser.EnumInjectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumInjection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumInjection([NotNull] mcdocParser.EnumInjectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.injection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInjection([NotNull] mcdocParser.InjectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.injection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInjection([NotNull] mcdocParser.InjectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.useStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseStatement([NotNull] mcdocParser.UseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.useStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseStatement([NotNull] mcdocParser.UseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParam([NotNull] mcdocParser.TypeParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParam([NotNull] mcdocParser.TypeParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeParamBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParamBlock([NotNull] mcdocParser.TypeParamBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeParamBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParamBlock([NotNull] mcdocParser.TypeParamBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeAlias([NotNull] mcdocParser.TypeAliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeAlias([NotNull] mcdocParser.TypeAliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructKey([NotNull] mcdocParser.StructKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructKey([NotNull] mcdocParser.StructKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructField([NotNull] mcdocParser.StructFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructField([NotNull] mcdocParser.StructFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructBlock([NotNull] mcdocParser.StructBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructBlock([NotNull] mcdocParser.StructBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct([NotNull] mcdocParser.StructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct([NotNull] mcdocParser.StructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] mcdocParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] mcdocParser.FileContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
