//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from mcdocParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="mcdocParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ImcdocParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.logicalOR"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOR([NotNull] mcdocParser.LogicalORContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] mcdocParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.resourceLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceLocation([NotNull] mcdocParser.ResourceLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.at"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt([NotNull] mcdocParser.AtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.as"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs([NotNull] mcdocParser.AsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.dot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDot([NotNull] mcdocParser.DotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.baseDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseDataType([NotNull] mcdocParser.BaseDataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.keywordType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeywordType([NotNull] mcdocParser.KeywordTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.questionMark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuestionMark([NotNull] mcdocParser.QuestionMarkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeKey([NotNull] mcdocParser.TypeKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.structKeyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructKeyType([NotNull] mcdocParser.StructKeyTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.inject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInject([NotNull] mcdocParser.InjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum([NotNull] mcdocParser.EnumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse([NotNull] mcdocParser.UseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.dispatch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatch([NotNull] mcdocParser.DispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.doubleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleDot([NotNull] mcdocParser.DoubleDotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.tripleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTripleDot([NotNull] mcdocParser.TripleDotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] mcdocParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] mcdocParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] mcdocParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.integerRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerRange([NotNull] mcdocParser.IntegerRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.floatRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatRange([NotNull] mcdocParser.FloatRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] mcdocParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolValue([NotNull] mcdocParser.BoolValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.commentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentary([NotNull] mcdocParser.CommentaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.docCommentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocCommentary([NotNull] mcdocParser.DocCommentaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typedNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedNumber([NotNull] mcdocParser.TypedNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringType([NotNull] mcdocParser.StringTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.literalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralType([NotNull] mcdocParser.LiteralTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericType([NotNull] mcdocParser.NumericTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.listType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListType([NotNull] mcdocParser.ListTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleType([NotNull] mcdocParser.TupleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumMemberType([NotNull] mcdocParser.EnumMemberTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] mcdocParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumField([NotNull] mcdocParser.EnumFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBlock([NotNull] mcdocParser.EnumBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumType([NotNull] mcdocParser.EnumTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.prelim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrelim([NotNull] mcdocParser.PrelimContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceType([NotNull] mcdocParser.ReferenceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.dispatcherType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatcherType([NotNull] mcdocParser.DispatcherTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionType([NotNull] mcdocParser.UnionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.staticIndexKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticIndexKey([NotNull] mcdocParser.StaticIndexKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor([NotNull] mcdocParser.AccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.accessorKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessorKey([NotNull] mcdocParser.AccessorKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.dynamicIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicIndex([NotNull] mcdocParser.DynamicIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] mcdocParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.indexBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexBody([NotNull] mcdocParser.IndexBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.indexingOnAType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexingOnAType([NotNull] mcdocParser.IndexingOnATypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeArgBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgBlock([NotNull] mcdocParser.TypeArgBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.unAttributedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnAttributedType([NotNull] mcdocParser.UnAttributedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSentence([NotNull] mcdocParser.TypeSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.positionalValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositionalValues([NotNull] mcdocParser.PositionalValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.namedValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedValue([NotNull] mcdocParser.NamedValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.namedValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedValues([NotNull] mcdocParser.NamedValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.treeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTreeBody([NotNull] mcdocParser.TreeBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.treeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTreeValue([NotNull] mcdocParser.TreeValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] mcdocParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] mcdocParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.dispatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatchStatement([NotNull] mcdocParser.DispatchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.structInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructInjection([NotNull] mcdocParser.StructInjectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.enumInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumInjection([NotNull] mcdocParser.EnumInjectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.injection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInjection([NotNull] mcdocParser.InjectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.useStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseStatement([NotNull] mcdocParser.UseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParam([NotNull] mcdocParser.TypeParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeParamBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParamBlock([NotNull] mcdocParser.TypeParamBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.typeAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAlias([NotNull] mcdocParser.TypeAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.structKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructKey([NotNull] mcdocParser.StructKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructField([NotNull] mcdocParser.StructFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBlock([NotNull] mcdocParser.StructBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] mcdocParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mcdocParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] mcdocParser.FileContext context);
}
