//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/C#Project/MinecraftLanguageServer/MCDocumentRule/mcdocParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="mcdocParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ImcdocParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.logicalOR"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOR([NotNull] mcdocParser.LogicalORContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.logicalOR"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOR([NotNull] mcdocParser.LogicalORContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] mcdocParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] mcdocParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.resourceLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResourceLocation([NotNull] mcdocParser.ResourceLocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.resourceLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResourceLocation([NotNull] mcdocParser.ResourceLocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.at"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAt([NotNull] mcdocParser.AtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.at"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAt([NotNull] mcdocParser.AtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.as"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAs([NotNull] mcdocParser.AsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.as"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAs([NotNull] mcdocParser.AsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot([NotNull] mcdocParser.DotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot([NotNull] mcdocParser.DotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.baseDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseDataType([NotNull] mcdocParser.BaseDataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.baseDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseDataType([NotNull] mcdocParser.BaseDataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.keywordType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordType([NotNull] mcdocParser.KeywordTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.keywordType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordType([NotNull] mcdocParser.KeywordTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.questionMark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuestionMark([NotNull] mcdocParser.QuestionMarkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.questionMark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuestionMark([NotNull] mcdocParser.QuestionMarkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeKey([NotNull] mcdocParser.TypeKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeKey([NotNull] mcdocParser.TypeKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structKeyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructKeyType([NotNull] mcdocParser.StructKeyTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structKeyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructKeyType([NotNull] mcdocParser.StructKeyTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.inject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInject([NotNull] mcdocParser.InjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.inject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInject([NotNull] mcdocParser.InjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum([NotNull] mcdocParser.EnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum([NotNull] mcdocParser.EnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUse([NotNull] mcdocParser.UseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUse([NotNull] mcdocParser.UseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDispatch([NotNull] mcdocParser.DispatchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDispatch([NotNull] mcdocParser.DispatchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.doubleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleDot([NotNull] mcdocParser.DoubleDotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.doubleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleDot([NotNull] mcdocParser.DoubleDotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.tripleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTripleDot([NotNull] mcdocParser.TripleDotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.tripleDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTripleDot([NotNull] mcdocParser.TripleDotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] mcdocParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] mcdocParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloat([NotNull] mcdocParser.FloatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloat([NotNull] mcdocParser.FloatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] mcdocParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] mcdocParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.integerRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerRange([NotNull] mcdocParser.IntegerRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.integerRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerRange([NotNull] mcdocParser.IntegerRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] mcdocParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] mcdocParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolValue([NotNull] mcdocParser.BoolValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolValue([NotNull] mcdocParser.BoolValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentary([NotNull] mcdocParser.CommentaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentary([NotNull] mcdocParser.CommentaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.docCommentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocCommentary([NotNull] mcdocParser.DocCommentaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.docCommentary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocCommentary([NotNull] mcdocParser.DocCommentaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typedNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedNumber([NotNull] mcdocParser.TypedNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typedNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedNumber([NotNull] mcdocParser.TypedNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringType([NotNull] mcdocParser.StringTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringType([NotNull] mcdocParser.StringTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.literalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralType([NotNull] mcdocParser.LiteralTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.literalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralType([NotNull] mcdocParser.LiteralTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericType([NotNull] mcdocParser.NumericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericType([NotNull] mcdocParser.NumericTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.listType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListType([NotNull] mcdocParser.ListTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.listType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListType([NotNull] mcdocParser.ListTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleType([NotNull] mcdocParser.TupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleType([NotNull] mcdocParser.TupleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumMemberType([NotNull] mcdocParser.EnumMemberTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumMemberType([NotNull] mcdocParser.EnumMemberTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValue([NotNull] mcdocParser.EnumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValue([NotNull] mcdocParser.EnumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumField([NotNull] mcdocParser.EnumFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumField([NotNull] mcdocParser.EnumFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBlock([NotNull] mcdocParser.EnumBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBlock([NotNull] mcdocParser.EnumBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumType([NotNull] mcdocParser.EnumTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumType([NotNull] mcdocParser.EnumTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.prelim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrelim([NotNull] mcdocParser.PrelimContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.prelim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrelim([NotNull] mcdocParser.PrelimContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceType([NotNull] mcdocParser.ReferenceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceType([NotNull] mcdocParser.ReferenceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatcherType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDispatcherType([NotNull] mcdocParser.DispatcherTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatcherType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDispatcherType([NotNull] mcdocParser.DispatcherTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionType([NotNull] mcdocParser.UnionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionType([NotNull] mcdocParser.UnionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.staticIndexKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticIndexKey([NotNull] mcdocParser.StaticIndexKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.staticIndexKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticIndexKey([NotNull] mcdocParser.StaticIndexKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessor([NotNull] mcdocParser.AccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessor([NotNull] mcdocParser.AccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.accessorKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessorKey([NotNull] mcdocParser.AccessorKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.accessorKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessorKey([NotNull] mcdocParser.AccessorKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dynamicIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDynamicIndex([NotNull] mcdocParser.DynamicIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dynamicIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDynamicIndex([NotNull] mcdocParser.DynamicIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] mcdocParser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] mcdocParser.IndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexBody([NotNull] mcdocParser.IndexBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexBody([NotNull] mcdocParser.IndexBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.indexingOnAType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexingOnAType([NotNull] mcdocParser.IndexingOnATypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.indexingOnAType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexingOnAType([NotNull] mcdocParser.IndexingOnATypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeArgBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgBlock([NotNull] mcdocParser.TypeArgBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeArgBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgBlock([NotNull] mcdocParser.TypeArgBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unAttributedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnAttributedType([NotNull] mcdocParser.UnAttributedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unAttributedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnAttributedType([NotNull] mcdocParser.UnAttributedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSentence([NotNull] mcdocParser.TypeSentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSentence([NotNull] mcdocParser.TypeSentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.positionalValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositionalValues([NotNull] mcdocParser.PositionalValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.positionalValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositionalValues([NotNull] mcdocParser.PositionalValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.namedValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedValue([NotNull] mcdocParser.NamedValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.namedValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedValue([NotNull] mcdocParser.NamedValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.namedValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedValues([NotNull] mcdocParser.NamedValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.namedValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedValues([NotNull] mcdocParser.NamedValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.treeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreeBody([NotNull] mcdocParser.TreeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.treeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreeBody([NotNull] mcdocParser.TreeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.treeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreeValue([NotNull] mcdocParser.TreeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.treeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreeValue([NotNull] mcdocParser.TreeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] mcdocParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] mcdocParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] mcdocParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] mcdocParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDispatchStatement([NotNull] mcdocParser.DispatchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDispatchStatement([NotNull] mcdocParser.DispatchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructInjection([NotNull] mcdocParser.StructInjectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructInjection([NotNull] mcdocParser.StructInjectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.enumInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumInjection([NotNull] mcdocParser.EnumInjectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.enumInjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumInjection([NotNull] mcdocParser.EnumInjectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.injection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInjection([NotNull] mcdocParser.InjectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.injection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInjection([NotNull] mcdocParser.InjectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.useStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUseStatement([NotNull] mcdocParser.UseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.useStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUseStatement([NotNull] mcdocParser.UseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParam([NotNull] mcdocParser.TypeParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParam([NotNull] mcdocParser.TypeParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeParamBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParamBlock([NotNull] mcdocParser.TypeParamBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeParamBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParamBlock([NotNull] mcdocParser.TypeParamBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.typeAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAlias([NotNull] mcdocParser.TypeAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.typeAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAlias([NotNull] mcdocParser.TypeAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructKey([NotNull] mcdocParser.StructKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructKey([NotNull] mcdocParser.StructKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructField([NotNull] mcdocParser.StructFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructField([NotNull] mcdocParser.StructFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructBlock([NotNull] mcdocParser.StructBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructBlock([NotNull] mcdocParser.StructBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct([NotNull] mcdocParser.StructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct([NotNull] mcdocParser.StructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] mcdocParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] mcdocParser.FileContext context);
}
