//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MCDocument/mcdoc.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ImcdocListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class mcdocBaseListener : ImcdocListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.arrayElementCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayElementCount([NotNull] mcdocParser.ArrayElementCountContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.arrayElementCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayElementCount([NotNull] mcdocParser.ArrayElementCountContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.arrayValueRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayValueRange([NotNull] mcdocParser.ArrayValueRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.arrayValueRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayValueRange([NotNull] mcdocParser.ArrayValueRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.summary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSummary([NotNull] mcdocParser.SummaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.summary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSummary([NotNull] mcdocParser.SummaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.fieldValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldValue([NotNull] mcdocParser.FieldValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.fieldValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldValue([NotNull] mcdocParser.FieldValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] mcdocParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.tupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] mcdocParser.TupleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unknownKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnknownKey([NotNull] mcdocParser.UnknownKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unknownKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnknownKey([NotNull] mcdocParser.UnknownKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unknownValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnknownValue([NotNull] mcdocParser.UnknownValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unknownValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnknownValue([NotNull] mcdocParser.UnknownValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.unknownResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnknownResource([NotNull] mcdocParser.UnknownResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.unknownResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnknownResource([NotNull] mcdocParser.UnknownResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.primitiveArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveArrayType([NotNull] mcdocParser.PrimitiveArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataType([NotNull] mcdocParser.DataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataType([NotNull] mcdocParser.DataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.canonical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCanonical([NotNull] mcdocParser.CanonicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.canonical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCanonical([NotNull] mcdocParser.CanonicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor([NotNull] mcdocParser.ColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor([NotNull] mcdocParser.ColorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commandSlashOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandSlashOptions([NotNull] mcdocParser.CommandSlashOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commandSlashOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandSlashOptions([NotNull] mcdocParser.CommandSlashOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commandMacroOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandMacroOptions([NotNull] mcdocParser.CommandMacroOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commandMacroOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandMacroOptions([NotNull] mcdocParser.CommandMacroOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commandEmptyOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandEmptyOptions([NotNull] mcdocParser.CommandEmptyOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commandEmptyOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandEmptyOptions([NotNull] mcdocParser.CommandEmptyOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commandMaxLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandMaxLength([NotNull] mcdocParser.CommandMaxLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commandMaxLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandMaxLength([NotNull] mcdocParser.CommandMaxLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.commandParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandParameters([NotNull] mcdocParser.CommandParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.commandParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandParameters([NotNull] mcdocParser.CommandParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] mcdocParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] mcdocParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.deprecated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeprecated([NotNull] mcdocParser.DeprecatedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.deprecated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeprecated([NotNull] mcdocParser.DeprecatedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatcher_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDispatcher_key([NotNull] mcdocParser.Dispatcher_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatcher_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDispatcher_key([NotNull] mcdocParser.Dispatcher_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.divisible_by"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivisible_by([NotNull] mcdocParser.Divisible_byContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.divisible_by"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivisible_by([NotNull] mcdocParser.Divisible_byContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.entityAmount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityAmount([NotNull] mcdocParser.EntityAmountContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.entityAmount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityAmount([NotNull] mcdocParser.EntityAmountContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.entityType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityType([NotNull] mcdocParser.EntityTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.entityType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityType([NotNull] mcdocParser.EntityTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.entityParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityParameters([NotNull] mcdocParser.EntityParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.entityParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityParameters([NotNull] mcdocParser.EntityParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntity([NotNull] mcdocParser.EntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntity([NotNull] mcdocParser.EntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.gameRuleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameRuleParameter([NotNull] mcdocParser.GameRuleParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.gameRuleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameRuleParameter([NotNull] mcdocParser.GameRuleParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.game_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGame_rule([NotNull] mcdocParser.Game_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.game_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGame_rule([NotNull] mcdocParser.Game_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.idRegistry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdRegistry([NotNull] mcdocParser.IdRegistryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.idRegistry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdRegistry([NotNull] mcdocParser.IdRegistryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.idTags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdTags([NotNull] mcdocParser.IdTagsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.idTags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdTags([NotNull] mcdocParser.IdTagsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.idParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdParameters([NotNull] mcdocParser.IdParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.idParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdParameters([NotNull] mcdocParser.IdParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] mcdocParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] mcdocParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.match_regex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatch_regex([NotNull] mcdocParser.Match_regexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.match_regex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatch_regex([NotNull] mcdocParser.Match_regexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.nbt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbt([NotNull] mcdocParser.NbtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.nbt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbt([NotNull] mcdocParser.NbtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.nbt_path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbt_path([NotNull] mcdocParser.Nbt_pathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.nbt_path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbt_path([NotNull] mcdocParser.Nbt_pathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.objective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjective([NotNull] mcdocParser.ObjectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.objective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjective([NotNull] mcdocParser.ObjectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.regex_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegex_pattern([NotNull] mcdocParser.Regex_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.regex_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegex_pattern([NotNull] mcdocParser.Regex_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.score_holder"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScore_holder([NotNull] mcdocParser.Score_holderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.score_holder"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScore_holder([NotNull] mcdocParser.Score_holderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.since"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSince([NotNull] mcdocParser.SinceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.since"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSince([NotNull] mcdocParser.SinceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.until"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUntil([NotNull] mcdocParser.UntilContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.until"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUntil([NotNull] mcdocParser.UntilContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] mcdocParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] mcdocParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.team"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeam([NotNull] mcdocParser.TeamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.team"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeam([NotNull] mcdocParser.TeamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.text_component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText_component([NotNull] mcdocParser.Text_componentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.text_component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText_component([NotNull] mcdocParser.Text_componentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.uuid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUuid([NotNull] mcdocParser.UuidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.uuid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUuid([NotNull] mcdocParser.UuidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.usefilePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsefilePath([NotNull] mcdocParser.UsefilePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.usefilePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsefilePath([NotNull] mcdocParser.UsefilePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.useSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseSentence([NotNull] mcdocParser.UseSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.useSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseSentence([NotNull] mcdocParser.UseSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributes([NotNull] mcdocParser.AttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributes([NotNull] mcdocParser.AttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.dispatchSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDispatchSentence([NotNull] mcdocParser.DispatchSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.dispatchSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDispatchSentence([NotNull] mcdocParser.DispatchSentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] mcdocParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] mcdocParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructReference([NotNull] mcdocParser.StructReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructReference([NotNull] mcdocParser.StructReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructName([NotNull] mcdocParser.StructNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructName([NotNull] mcdocParser.StructNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structOpenBracket"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructOpenBracket([NotNull] mcdocParser.StructOpenBracketContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structOpenBracket"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructOpenBracket([NotNull] mcdocParser.StructOpenBracketContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structCloseBracket"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructCloseBracket([NotNull] mcdocParser.StructCloseBracketContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structCloseBracket"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructCloseBracket([NotNull] mcdocParser.StructCloseBracketContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.superInvoke"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperInvoke([NotNull] mcdocParser.SuperInvokeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.superInvoke"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperInvoke([NotNull] mcdocParser.SuperInvokeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructContent([NotNull] mcdocParser.StructContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructContent([NotNull] mcdocParser.StructContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mcdocParser.structSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructSentence([NotNull] mcdocParser.StructSentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mcdocParser.structSentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructSentence([NotNull] mcdocParser.StructSentenceContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
