//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/C#Projects/AutoComplete/Grammar/commonNBTTrees.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="commonNBTTreesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IcommonNBTTreesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] commonNBTTreesParser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] commonNBTTreesParser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.trees"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrees([NotNull] commonNBTTreesParser.TreesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.trees"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrees([NotNull] commonNBTTreesParser.TreesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.itemCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemCommonTags([NotNull] commonNBTTreesParser.ItemCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.itemCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemCommonTags([NotNull] commonNBTTreesParser.ItemCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCount([NotNull] commonNBTTreesParser.CountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCount([NotNull] commonNBTTreesParser.CountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] commonNBTTreesParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] commonNBTTreesParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlot([NotNull] commonNBTTreesParser.SlotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlot([NotNull] commonNBTTreesParser.SlotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTag([NotNull] commonNBTTreesParser.TagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTag([NotNull] commonNBTTreesParser.TagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.attributeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeModifiers([NotNull] commonNBTTreesParser.AttributeModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.attributeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeModifiers([NotNull] commonNBTTreesParser.AttributeModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.attributeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeModifier([NotNull] commonNBTTreesParser.AttributeModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.attributeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeModifier([NotNull] commonNBTTreesParser.AttributeModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.amount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmount([NotNull] commonNBTTreesParser.AmountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.amount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmount([NotNull] commonNBTTreesParser.AmountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeName([NotNull] commonNBTTreesParser.AttributeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeName([NotNull] commonNBTTreesParser.AttributeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] commonNBTTreesParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] commonNBTTreesParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] commonNBTTreesParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] commonNBTTreesParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.attributeSlot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeSlot([NotNull] commonNBTTreesParser.AttributeSlotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.attributeSlot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeSlot([NotNull] commonNBTTreesParser.AttributeSlotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.uuid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUuid([NotNull] commonNBTTreesParser.UuidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.uuid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUuid([NotNull] commonNBTTreesParser.UuidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.canDestroy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCanDestroy([NotNull] commonNBTTreesParser.CanDestroyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.canDestroy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCanDestroy([NotNull] commonNBTTreesParser.CanDestroyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.customCreativeLock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomCreativeLock([NotNull] commonNBTTreesParser.CustomCreativeLockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.customCreativeLock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomCreativeLock([NotNull] commonNBTTreesParser.CustomCreativeLockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.customModelData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomModelData([NotNull] commonNBTTreesParser.CustomModelDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.customModelData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomModelData([NotNull] commonNBTTreesParser.CustomModelDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.damage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDamage([NotNull] commonNBTTreesParser.DamageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.damage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDamage([NotNull] commonNBTTreesParser.DamageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.display"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplay([NotNull] commonNBTTreesParser.DisplayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.display"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplay([NotNull] commonNBTTreesParser.DisplayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColor([NotNull] commonNBTTreesParser.ColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColor([NotNull] commonNBTTreesParser.ColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.lore"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLore([NotNull] commonNBTTreesParser.LoreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.lore"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLore([NotNull] commonNBTTreesParser.LoreContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.jsonText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonText([NotNull] commonNBTTreesParser.JsonTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.jsonText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonText([NotNull] commonNBTTreesParser.JsonTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.enchantments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnchantments([NotNull] commonNBTTreesParser.EnchantmentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.enchantments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnchantments([NotNull] commonNBTTreesParser.EnchantmentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.enchantment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnchantment([NotNull] commonNBTTreesParser.EnchantmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.enchantment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnchantment([NotNull] commonNBTTreesParser.EnchantmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.lvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvl([NotNull] commonNBTTreesParser.LvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.lvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvl([NotNull] commonNBTTreesParser.LvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hideFlags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHideFlags([NotNull] commonNBTTreesParser.HideFlagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hideFlags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHideFlags([NotNull] commonNBTTreesParser.HideFlagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.repairCost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepairCost([NotNull] commonNBTTreesParser.RepairCostContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.repairCost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepairCost([NotNull] commonNBTTreesParser.RepairCostContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.trim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrim([NotNull] commonNBTTreesParser.TrimContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.trim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrim([NotNull] commonNBTTreesParser.TrimContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.material"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterial([NotNull] commonNBTTreesParser.MaterialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.material"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterial([NotNull] commonNBTTreesParser.MaterialContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern([NotNull] commonNBTTreesParser.PatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern([NotNull] commonNBTTreesParser.PatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.unbreakable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnbreakable([NotNull] commonNBTTreesParser.UnbreakableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.unbreakable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnbreakable([NotNull] commonNBTTreesParser.UnbreakableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.angryCreatureExtraField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAngryCreatureExtraField([NotNull] commonNBTTreesParser.AngryCreatureExtraFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.angryCreatureExtraField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAngryCreatureExtraField([NotNull] commonNBTTreesParser.AngryCreatureExtraFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.angerTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAngerTime([NotNull] commonNBTTreesParser.AngerTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.angerTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAngerTime([NotNull] commonNBTTreesParser.AngerTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.angryAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAngryAt([NotNull] commonNBTTreesParser.AngryAtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.angryAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAngryAt([NotNull] commonNBTTreesParser.AngryAtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.cannotEnterHiveTicks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCannotEnterHiveTicks([NotNull] commonNBTTreesParser.CannotEnterHiveTicksContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.cannotEnterHiveTicks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCannotEnterHiveTicks([NotNull] commonNBTTreesParser.CannotEnterHiveTicksContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.cropsGrownSincePollination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCropsGrownSincePollination([NotNull] commonNBTTreesParser.CropsGrownSincePollinationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.cropsGrownSincePollination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCropsGrownSincePollination([NotNull] commonNBTTreesParser.CropsGrownSincePollinationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.flowerPos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlowerPos([NotNull] commonNBTTreesParser.FlowerPosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.flowerPos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlowerPos([NotNull] commonNBTTreesParser.FlowerPosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hasNectar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHasNectar([NotNull] commonNBTTreesParser.HasNectarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hasNectar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHasNectar([NotNull] commonNBTTreesParser.HasNectarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hasStung"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHasStung([NotNull] commonNBTTreesParser.HasStungContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hasStung"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHasStung([NotNull] commonNBTTreesParser.HasStungContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hivePos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHivePos([NotNull] commonNBTTreesParser.HivePosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hivePos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHivePos([NotNull] commonNBTTreesParser.HivePosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.ticksSincePollination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTicksSincePollination([NotNull] commonNBTTreesParser.TicksSincePollinationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.ticksSincePollination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTicksSincePollination([NotNull] commonNBTTreesParser.TicksSincePollinationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.arrowProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrowProjectileCommonTags([NotNull] commonNBTTreesParser.ArrowProjectileCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.arrowProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrowProjectileCommonTags([NotNull] commonNBTTreesParser.ArrowProjectileCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.crit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrit([NotNull] commonNBTTreesParser.CritContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.crit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrit([NotNull] commonNBTTreesParser.CritContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.shotFromCrossbow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShotFromCrossbow([NotNull] commonNBTTreesParser.ShotFromCrossbowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.shotFromCrossbow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShotFromCrossbow([NotNull] commonNBTTreesParser.ShotFromCrossbowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.soundEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoundEvent([NotNull] commonNBTTreesParser.SoundEventContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.soundEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoundEvent([NotNull] commonNBTTreesParser.SoundEventContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.inGround"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInGround([NotNull] commonNBTTreesParser.InGroundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.inGround"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInGround([NotNull] commonNBTTreesParser.InGroundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.pickup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPickup([NotNull] commonNBTTreesParser.PickupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.pickup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPickup([NotNull] commonNBTTreesParser.PickupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.pierceLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPierceLevel([NotNull] commonNBTTreesParser.PierceLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.pierceLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPierceLevel([NotNull] commonNBTTreesParser.PierceLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.shake"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShake([NotNull] commonNBTTreesParser.ShakeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.shake"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShake([NotNull] commonNBTTreesParser.ShakeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.life"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLife([NotNull] commonNBTTreesParser.LifeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.life"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLife([NotNull] commonNBTTreesParser.LifeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.arrowDamage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrowDamage([NotNull] commonNBTTreesParser.ArrowDamageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.arrowDamage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrowDamage([NotNull] commonNBTTreesParser.ArrowDamageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.inBlockState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInBlockState([NotNull] commonNBTTreesParser.InBlockStateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.inBlockState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInBlockState([NotNull] commonNBTTreesParser.InBlockStateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.blockStateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStateName([NotNull] commonNBTTreesParser.BlockStateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.blockStateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStateName([NotNull] commonNBTTreesParser.BlockStateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.blockStateProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStateProperties([NotNull] commonNBTTreesParser.BlockStatePropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.blockStateProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStateProperties([NotNull] commonNBTTreesParser.BlockStatePropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.propertiesKeyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertiesKeyValuePair([NotNull] commonNBTTreesParser.PropertiesKeyValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.propertiesKeyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertiesKeyValuePair([NotNull] commonNBTTreesParser.PropertiesKeyValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.propertiesKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertiesKey([NotNull] commonNBTTreesParser.PropertiesKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.propertiesKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertiesKey([NotNull] commonNBTTreesParser.PropertiesKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.propertiesValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertiesValue([NotNull] commonNBTTreesParser.PropertiesValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.propertiesValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertiesValue([NotNull] commonNBTTreesParser.PropertiesValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.breedableMobExtraFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreedableMobExtraFields([NotNull] commonNBTTreesParser.BreedableMobExtraFieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.breedableMobExtraFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreedableMobExtraFields([NotNull] commonNBTTreesParser.BreedableMobExtraFieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.age"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAge([NotNull] commonNBTTreesParser.AgeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.age"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAge([NotNull] commonNBTTreesParser.AgeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.forcedAge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForcedAge([NotNull] commonNBTTreesParser.ForcedAgeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.forcedAge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForcedAge([NotNull] commonNBTTreesParser.ForcedAgeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.inLove"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInLove([NotNull] commonNBTTreesParser.InLoveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.inLove"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInLove([NotNull] commonNBTTreesParser.InLoveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.loveCause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoveCause([NotNull] commonNBTTreesParser.LoveCauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.loveCause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoveCause([NotNull] commonNBTTreesParser.LoveCauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForMobsSpawnedInRaids"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonTagsForMobsSpawnedInRaids([NotNull] commonNBTTreesParser.CommonTagsForMobsSpawnedInRaidsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForMobsSpawnedInRaids"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonTagsForMobsSpawnedInRaids([NotNull] commonNBTTreesParser.CommonTagsForMobsSpawnedInRaidsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.canJoinRaid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCanJoinRaid([NotNull] commonNBTTreesParser.CanJoinRaidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.canJoinRaid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCanJoinRaid([NotNull] commonNBTTreesParser.CanJoinRaidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.patrolLeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatrolLeader([NotNull] commonNBTTreesParser.PatrolLeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.patrolLeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatrolLeader([NotNull] commonNBTTreesParser.PatrolLeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.patrolling"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatrolling([NotNull] commonNBTTreesParser.PatrollingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.patrolling"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatrolling([NotNull] commonNBTTreesParser.PatrollingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.patrolTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatrolTarget([NotNull] commonNBTTreesParser.PatrolTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.patrolTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatrolTarget([NotNull] commonNBTTreesParser.PatrolTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.raidId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaidId([NotNull] commonNBTTreesParser.RaidIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.raidId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaidId([NotNull] commonNBTTreesParser.RaidIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.wave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWave([NotNull] commonNBTTreesParser.WaveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.wave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWave([NotNull] commonNBTTreesParser.WaveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForRideableEntities"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonTagsForRideableEntities([NotNull] commonNBTTreesParser.CommonTagsForRideableEntitiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForRideableEntities"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonTagsForRideableEntities([NotNull] commonNBTTreesParser.CommonTagsForRideableEntitiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.bred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBred([NotNull] commonNBTTreesParser.BredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.bred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBred([NotNull] commonNBTTreesParser.BredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.eatingHaystack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEatingHaystack([NotNull] commonNBTTreesParser.EatingHaystackContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.eatingHaystack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEatingHaystack([NotNull] commonNBTTreesParser.EatingHaystackContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.owner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOwner([NotNull] commonNBTTreesParser.OwnerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.owner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOwner([NotNull] commonNBTTreesParser.OwnerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.tame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTame([NotNull] commonNBTTreesParser.TameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.tame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTame([NotNull] commonNBTTreesParser.TameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.temper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemper([NotNull] commonNBTTreesParser.TemperContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.temper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemper([NotNull] commonNBTTreesParser.TemperContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForZombies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonTagsForZombies([NotNull] commonNBTTreesParser.CommonTagsForZombiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.commonTagsForZombies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonTagsForZombies([NotNull] commonNBTTreesParser.CommonTagsForZombiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.canBreakDoors"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCanBreakDoors([NotNull] commonNBTTreesParser.CanBreakDoorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.canBreakDoors"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCanBreakDoors([NotNull] commonNBTTreesParser.CanBreakDoorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.drownedConversionTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrownedConversionTime([NotNull] commonNBTTreesParser.DrownedConversionTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.drownedConversionTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrownedConversionTime([NotNull] commonNBTTreesParser.DrownedConversionTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.inWaterTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInWaterTime([NotNull] commonNBTTreesParser.InWaterTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.inWaterTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInWaterTime([NotNull] commonNBTTreesParser.InWaterTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.isBaby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsBaby([NotNull] commonNBTTreesParser.IsBabyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.isBaby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsBaby([NotNull] commonNBTTreesParser.IsBabyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.containerEntityCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainerEntityCommonTags([NotNull] commonNBTTreesParser.ContainerEntityCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.containerEntityCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainerEntityCommonTags([NotNull] commonNBTTreesParser.ContainerEntityCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.lootTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLootTable([NotNull] commonNBTTreesParser.LootTableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.lootTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLootTable([NotNull] commonNBTTreesParser.LootTableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.lootTableSeed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLootTableSeed([NotNull] commonNBTTreesParser.LootTableSeedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.lootTableSeed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLootTableSeed([NotNull] commonNBTTreesParser.LootTableSeedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.containerItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainerItems([NotNull] commonNBTTreesParser.ContainerItemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.containerItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainerItems([NotNull] commonNBTTreesParser.ContainerItemsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.entityCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityCommonTags([NotNull] commonNBTTreesParser.EntityCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.entityCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityCommonTags([NotNull] commonNBTTreesParser.EntityCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.air"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAir([NotNull] commonNBTTreesParser.AirContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.air"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAir([NotNull] commonNBTTreesParser.AirContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.customName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomName([NotNull] commonNBTTreesParser.CustomNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.customName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomName([NotNull] commonNBTTreesParser.CustomNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.customNameVisible"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomNameVisible([NotNull] commonNBTTreesParser.CustomNameVisibleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.customNameVisible"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomNameVisible([NotNull] commonNBTTreesParser.CustomNameVisibleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.fallDistance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFallDistance([NotNull] commonNBTTreesParser.FallDistanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.fallDistance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFallDistance([NotNull] commonNBTTreesParser.FallDistanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.fire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFire([NotNull] commonNBTTreesParser.FireContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.fire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFire([NotNull] commonNBTTreesParser.FireContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.glowing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlowing([NotNull] commonNBTTreesParser.GlowingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.glowing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlowing([NotNull] commonNBTTreesParser.GlowingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hasVisualFire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHasVisualFire([NotNull] commonNBTTreesParser.HasVisualFireContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hasVisualFire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHasVisualFire([NotNull] commonNBTTreesParser.HasVisualFireContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.invulnerable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvulnerable([NotNull] commonNBTTreesParser.InvulnerableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.invulnerable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvulnerable([NotNull] commonNBTTreesParser.InvulnerableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.motion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMotion([NotNull] commonNBTTreesParser.MotionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.motion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMotion([NotNull] commonNBTTreesParser.MotionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.noGravity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoGravity([NotNull] commonNBTTreesParser.NoGravityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.noGravity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoGravity([NotNull] commonNBTTreesParser.NoGravityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.portalCooldown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPortalCooldown([NotNull] commonNBTTreesParser.PortalCooldownContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.portalCooldown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPortalCooldown([NotNull] commonNBTTreesParser.PortalCooldownContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.rotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotation([NotNull] commonNBTTreesParser.RotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.rotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotation([NotNull] commonNBTTreesParser.RotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.silent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSilent([NotNull] commonNBTTreesParser.SilentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.silent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSilent([NotNull] commonNBTTreesParser.SilentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTags([NotNull] commonNBTTreesParser.TagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTags([NotNull] commonNBTTreesParser.TagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.ticksFrozen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTicksFrozen([NotNull] commonNBTTreesParser.TicksFrozenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.ticksFrozen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTicksFrozen([NotNull] commonNBTTreesParser.TicksFrozenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.passengers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassengers([NotNull] commonNBTTreesParser.PassengersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.passengers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassengers([NotNull] commonNBTTreesParser.PassengersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.entityData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityData([NotNull] commonNBTTreesParser.EntityDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.entityData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityData([NotNull] commonNBTTreesParser.EntityDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.fireballProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFireballProjectileCommonTags([NotNull] commonNBTTreesParser.FireballProjectileCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.fireballProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFireballProjectileCommonTags([NotNull] commonNBTTreesParser.FireballProjectileCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] commonNBTTreesParser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] commonNBTTreesParser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.itemProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemProjectileCommonTags([NotNull] commonNBTTreesParser.ItemProjectileCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.itemProjectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemProjectileCommonTags([NotNull] commonNBTTreesParser.ItemProjectileCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.itemProjectileItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemProjectileItem([NotNull] commonNBTTreesParser.ItemProjectileItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.itemProjectileItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemProjectileItem([NotNull] commonNBTTreesParser.ItemProjectileItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyCommonTags([NotNull] commonNBTTreesParser.LivingBodyCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyCommonTags([NotNull] commonNBTTreesParser.LivingBodyCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.absorptionAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsorptionAmount([NotNull] commonNBTTreesParser.AbsorptionAmountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.absorptionAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsorptionAmount([NotNull] commonNBTTreesParser.AbsorptionAmountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.deathTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeathTime([NotNull] commonNBTTreesParser.DeathTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.deathTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeathTime([NotNull] commonNBTTreesParser.DeathTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.fallFlying"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFallFlying([NotNull] commonNBTTreesParser.FallFlyingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.fallFlying"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFallFlying([NotNull] commonNBTTreesParser.FallFlyingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.health"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHealth([NotNull] commonNBTTreesParser.HealthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.health"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHealth([NotNull] commonNBTTreesParser.HealthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hurtByTimestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHurtByTimestamp([NotNull] commonNBTTreesParser.HurtByTimestampContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hurtByTimestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHurtByTimestamp([NotNull] commonNBTTreesParser.HurtByTimestampContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hurtTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHurtTime([NotNull] commonNBTTreesParser.HurtTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hurtTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHurtTime([NotNull] commonNBTTreesParser.HurtTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.sleepingX"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSleepingX([NotNull] commonNBTTreesParser.SleepingXContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.sleepingX"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSleepingX([NotNull] commonNBTTreesParser.SleepingXContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.sleepingY"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSleepingY([NotNull] commonNBTTreesParser.SleepingYContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.sleepingY"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSleepingY([NotNull] commonNBTTreesParser.SleepingYContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.sleepingZ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSleepingZ([NotNull] commonNBTTreesParser.SleepingZContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.sleepingZ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSleepingZ([NotNull] commonNBTTreesParser.SleepingZContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyAttributes([NotNull] commonNBTTreesParser.LivingBodyAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyAttributes([NotNull] commonNBTTreesParser.LivingBodyAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyAttribute([NotNull] commonNBTTreesParser.LivingBodyAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyAttribute([NotNull] commonNBTTreesParser.LivingBodyAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase([NotNull] commonNBTTreesParser.BaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase([NotNull] commonNBTTreesParser.BaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyModifiers([NotNull] commonNBTTreesParser.LivingBodyModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyModifiers([NotNull] commonNBTTreesParser.LivingBodyModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModify"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyModify([NotNull] commonNBTTreesParser.LivingBodyModifyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModify"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyModify([NotNull] commonNBTTreesParser.LivingBodyModifyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyAmount([NotNull] commonNBTTreesParser.LivingBodyAmountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyAmount([NotNull] commonNBTTreesParser.LivingBodyAmountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModifyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyModifyName([NotNull] commonNBTTreesParser.LivingBodyModifyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyModifyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyModifyName([NotNull] commonNBTTreesParser.LivingBodyModifyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyOperation([NotNull] commonNBTTreesParser.LivingBodyOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyOperation([NotNull] commonNBTTreesParser.LivingBodyOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyName([NotNull] commonNBTTreesParser.LivingBodyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyName([NotNull] commonNBTTreesParser.LivingBodyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyActiveEffects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyActiveEffects([NotNull] commonNBTTreesParser.LivingBodyActiveEffectsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyActiveEffects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyActiveEffects([NotNull] commonNBTTreesParser.LivingBodyActiveEffectsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.livingBodyActiveEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLivingBodyActiveEffect([NotNull] commonNBTTreesParser.LivingBodyActiveEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.livingBodyActiveEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLivingBodyActiveEffect([NotNull] commonNBTTreesParser.LivingBodyActiveEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.ambient"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmbient([NotNull] commonNBTTreesParser.AmbientContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.ambient"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmbient([NotNull] commonNBTTreesParser.AmbientContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.amplifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmplifier([NotNull] commonNBTTreesParser.AmplifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.amplifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmplifier([NotNull] commonNBTTreesParser.AmplifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDuration([NotNull] commonNBTTreesParser.DurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDuration([NotNull] commonNBTTreesParser.DurationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.factor_calculation_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_calculation_data([NotNull] commonNBTTreesParser.Factor_calculation_dataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.factor_calculation_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_calculation_data([NotNull] commonNBTTreesParser.Factor_calculation_dataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.effect_changed_timestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEffect_changed_timestamp([NotNull] commonNBTTreesParser.Effect_changed_timestampContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.effect_changed_timestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEffect_changed_timestamp([NotNull] commonNBTTreesParser.Effect_changed_timestampContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.factor_current"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_current([NotNull] commonNBTTreesParser.Factor_currentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.factor_current"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_current([NotNull] commonNBTTreesParser.Factor_currentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.factor_previous_frame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_previous_frame([NotNull] commonNBTTreesParser.Factor_previous_frameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.factor_previous_frame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_previous_frame([NotNull] commonNBTTreesParser.Factor_previous_frameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.factor_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_start([NotNull] commonNBTTreesParser.Factor_startContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.factor_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_start([NotNull] commonNBTTreesParser.Factor_startContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.factor_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_target([NotNull] commonNBTTreesParser.Factor_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.factor_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_target([NotNull] commonNBTTreesParser.Factor_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.had_effect_last_tick"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHad_effect_last_tick([NotNull] commonNBTTreesParser.Had_effect_last_tickContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.had_effect_last_tick"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHad_effect_last_tick([NotNull] commonNBTTreesParser.Had_effect_last_tickContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.padding_duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPadding_duration([NotNull] commonNBTTreesParser.Padding_durationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.padding_duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPadding_duration([NotNull] commonNBTTreesParser.Padding_durationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.show_icon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShow_icon([NotNull] commonNBTTreesParser.Show_iconContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.show_icon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShow_icon([NotNull] commonNBTTreesParser.Show_iconContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.show_particles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShow_particles([NotNull] commonNBTTreesParser.Show_particlesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.show_particles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShow_particles([NotNull] commonNBTTreesParser.Show_particlesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.mineCartCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMineCartCommonTags([NotNull] commonNBTTreesParser.MineCartCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.mineCartCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMineCartCommonTags([NotNull] commonNBTTreesParser.MineCartCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.customDisplayTile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomDisplayTile([NotNull] commonNBTTreesParser.CustomDisplayTileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.customDisplayTile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomDisplayTile([NotNull] commonNBTTreesParser.CustomDisplayTileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.displayOffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayOffset([NotNull] commonNBTTreesParser.DisplayOffsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.displayOffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayOffset([NotNull] commonNBTTreesParser.DisplayOffsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.displayState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayState([NotNull] commonNBTTreesParser.DisplayStateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.displayState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayState([NotNull] commonNBTTreesParser.DisplayStateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.mobCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMobCommonTags([NotNull] commonNBTTreesParser.MobCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.mobCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMobCommonTags([NotNull] commonNBTTreesParser.MobCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.canPickUpLoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCanPickUpLoot([NotNull] commonNBTTreesParser.CanPickUpLootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.canPickUpLoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCanPickUpLoot([NotNull] commonNBTTreesParser.CanPickUpLootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.deathLootTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeathLootTable([NotNull] commonNBTTreesParser.DeathLootTableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.deathLootTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeathLootTable([NotNull] commonNBTTreesParser.DeathLootTableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.deathLootTableSeed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeathLootTableSeed([NotNull] commonNBTTreesParser.DeathLootTableSeedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.deathLootTableSeed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeathLootTableSeed([NotNull] commonNBTTreesParser.DeathLootTableSeedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.leftHanded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftHanded([NotNull] commonNBTTreesParser.LeftHandedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.leftHanded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftHanded([NotNull] commonNBTTreesParser.LeftHandedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.noAI"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoAI([NotNull] commonNBTTreesParser.NoAIContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.noAI"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoAI([NotNull] commonNBTTreesParser.NoAIContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.persistenceRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPersistenceRequired([NotNull] commonNBTTreesParser.PersistenceRequiredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.persistenceRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPersistenceRequired([NotNull] commonNBTTreesParser.PersistenceRequiredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.leash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeash([NotNull] commonNBTTreesParser.LeashContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.leash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeash([NotNull] commonNBTTreesParser.LeashContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.armorItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArmorItems([NotNull] commonNBTTreesParser.ArmorItemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.armorItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArmorItems([NotNull] commonNBTTreesParser.ArmorItemsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.armorDropChances"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArmorDropChances([NotNull] commonNBTTreesParser.ArmorDropChancesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.armorDropChances"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArmorDropChances([NotNull] commonNBTTreesParser.ArmorDropChancesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.handItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandItems([NotNull] commonNBTTreesParser.HandItemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.handItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandItems([NotNull] commonNBTTreesParser.HandItemsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.handDropChances"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandDropChances([NotNull] commonNBTTreesParser.HandDropChancesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.handDropChances"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandDropChances([NotNull] commonNBTTreesParser.HandDropChancesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.projectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProjectileCommonTags([NotNull] commonNBTTreesParser.ProjectileCommonTagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.projectileCommonTags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProjectileCommonTags([NotNull] commonNBTTreesParser.ProjectileCommonTagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.hasBeenShot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHasBeenShot([NotNull] commonNBTTreesParser.HasBeenShotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.hasBeenShot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHasBeenShot([NotNull] commonNBTTreesParser.HasBeenShotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.leftOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftOwner([NotNull] commonNBTTreesParser.LeftOwnerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.leftOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftOwner([NotNull] commonNBTTreesParser.LeftOwnerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.tameableMobExtraFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTameableMobExtraFields([NotNull] commonNBTTreesParser.TameableMobExtraFieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.tameableMobExtraFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTameableMobExtraFields([NotNull] commonNBTTreesParser.TameableMobExtraFieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="commonNBTTreesParser.sitting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSitting([NotNull] commonNBTTreesParser.SittingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="commonNBTTreesParser.sitting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSitting([NotNull] commonNBTTreesParser.SittingContext context);
}
