//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/C#Projects/AutoComplete/Grammar/selector.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IselectorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class selectorBaseListener : IselectorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] selectorParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] selectorParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.intInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntInterval([NotNull] selectorParser.IntIntervalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.intInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntInterval([NotNull] selectorParser.IntIntervalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] selectorParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] selectorParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.positiveNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositiveNumber([NotNull] selectorParser.PositiveNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.positiveNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositiveNumber([NotNull] selectorParser.PositiveNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.double"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble([NotNull] selectorParser.DoubleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.double"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble([NotNull] selectorParser.DoubleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.positiveDouble"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositiveDouble([NotNull] selectorParser.PositiveDoubleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.positiveDouble"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositiveDouble([NotNull] selectorParser.PositiveDoubleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.doubleInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleInterval([NotNull] selectorParser.DoubleIntervalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.doubleInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleInterval([NotNull] selectorParser.DoubleIntervalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.positiveDoubleInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositiveDoubleInterval([NotNull] selectorParser.PositiveDoubleIntervalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.positiveDoubleInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositiveDoubleInterval([NotNull] selectorParser.PositiveDoubleIntervalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.gamemodeValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGamemodeValues([NotNull] selectorParser.GamemodeValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.gamemodeValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGamemodeValues([NotNull] selectorParser.GamemodeValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.entityId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityId([NotNull] selectorParser.EntityIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.entityId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityId([NotNull] selectorParser.EntityIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] selectorParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] selectorParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.selectorTagValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectorTagValue([NotNull] selectorParser.SelectorTagValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.selectorTagValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectorTagValue([NotNull] selectorParser.SelectorTagValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.selectorTeamValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectorTeamValue([NotNull] selectorParser.SelectorTeamValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.selectorTeamValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectorTeamValue([NotNull] selectorParser.SelectorTeamValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.nameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameValue([NotNull] selectorParser.NameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.nameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameValue([NotNull] selectorParser.NameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.predicateValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateValue([NotNull] selectorParser.PredicateValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.predicateValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateValue([NotNull] selectorParser.PredicateValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.nameSpace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameSpace([NotNull] selectorParser.NameSpaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.nameSpace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameSpace([NotNull] selectorParser.NameSpaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.targetObjective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTargetObjective([NotNull] selectorParser.TargetObjectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.targetObjective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTargetObjective([NotNull] selectorParser.TargetObjectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.sortValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortValues([NotNull] selectorParser.SortValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.sortValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortValues([NotNull] selectorParser.SortValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonValue([NotNull] selectorParser.JsonValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonValue([NotNull] selectorParser.JsonValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.advancementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdvancementValue([NotNull] selectorParser.AdvancementValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.advancementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdvancementValue([NotNull] selectorParser.AdvancementValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.scoreParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScoreParameter([NotNull] selectorParser.ScoreParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.scoreParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScoreParameter([NotNull] selectorParser.ScoreParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.scoresValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScoresValue([NotNull] selectorParser.ScoresValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.scoresValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScoresValue([NotNull] selectorParser.ScoresValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.selectorParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectorParameters([NotNull] selectorParser.SelectorParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.selectorParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectorParameters([NotNull] selectorParser.SelectorParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="selectorParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] selectorParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="selectorParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] selectorParser.ParameterContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
